webtalk_init -webtalk_dir C:/Users/Nana/6111Projects/Ball_cols4/Ball_cols4.sim/sim_1/behav/xsim/xsim.dir/top_level_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Dec 11 01:23:43 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2711e3f7-6467-4d2c-90ad-ebd7f32928b5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3da21455af0f4a55a6fc54185040ecb8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "80" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "13 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "8" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.58_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10960_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2942665898 -regid "" -xml C:/Users/Nana/6111Projects/Ball_cols4/Ball_cols4.sim/sim_1/behav/xsim/xsim.dir/top_level_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Nana/6111Projects/Ball_cols4/Ball_cols4.sim/sim_1/behav/xsim/xsim.dir/top_level_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Nana/6111Projects/Ball_cols4/Ball_cols4.sim/sim_1/behav/xsim/xsim.dir/top_level_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
