# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Nana/6111Projects/Balls_col2/Balls_col2.srcs/sources_1/ip/frame_blk_mem/frame_blk_mem.xci
# IP: The module: 'frame_blk_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nana/6111Projects/Balls_col2/Balls_col2.srcs/sources_1/ip/frame_blk_mem/frame_blk_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_blk_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Nana/6111Projects/Balls_col2/Balls_col2.srcs/sources_1/ip/frame_blk_mem/frame_blk_mem.xci
# IP: The module: 'frame_blk_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nana/6111Projects/Balls_col2/Balls_col2.srcs/sources_1/ip/frame_blk_mem/frame_blk_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_blk_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
